---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE_ACCOUNT_BY_CONNECTOR}
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_IDENTITY_CLIENT_ID}
---
apiVersion: v1
kind: Service
metadata:
  name: worker-headless
spec:
  clusterIP: None
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT_BY_CONNECTOR}
      containers:
      - name: worker
        image: mapreducecontainers.azurecr.io/worker:latest
        ports:
        - containerPort: 50051
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: AZURE_STORAGE_ACCOUNT
          value: "mapreduceblob"
        - name: FAIL
          value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstable-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT_BY_CONNECTOR}
      containers:
      - name: worker
        image: mapreducecontainers.azurecr.io/worker:latest
        ports:
        - containerPort: 50051
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: AZURE_STORAGE_ACCOUNT
          value: "mapreduceblob"
        - name: FAIL
          value: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT_BY_CONNECTOR}
      containers:
      initContainers:
      - name: wait-for-workers
        image: busybox
        command: ['sh', '-c', 'until nslookup worker-headless.default.svc.cluster.local; do echo waiting for workers; sleep 2; done;']
      containers:
      - name: master
        image: mapreducecontainers.azurecr.io/master:latest
        ports:
        - containerPort: 50052 # grpc
        - containerPort: 30000 # http port for cli 
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: WORKER_SERVICE
          value: "worker-headless.default.svc.cluster.local"
        - name: MASTER_SERVICE
          value: "master-headless.default.svc.cluster.local"
        - name: AZURE_STORAGE_ACCOUNT
          value: "mapreduceblob"
        - name: FAIL
          value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstable-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT_BY_CONNECTOR}
      containers:
      initContainers:
      - name: wait-for-workers
        image: busybox
        command: ['sh', '-c', 'until nslookup worker-headless.default.svc.cluster.local; do echo waiting for workers; sleep 2; done;']
      containers:
      - name: master
        image: mapreducecontainers.azurecr.io/master:latest
        ports:
        - containerPort: 50052 # grpc
        - containerPort: 30000 # http port for cli 
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: WORKER_SERVICE
          value: "worker-headless.default.svc.cluster.local"
        - name: MASTER_SERVICE
          value: "master-headless.default.svc.cluster.local"
        - name: AZURE_STORAGE_ACCOUNT
          value: "mapreduceblob"
        - name: FAIL
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: LoadBalancer 
  selector:
    app: master
  ports:
  - name: http
    port: 30001 # service port
    targetPort: 30000 # container port (internal access port)
---
apiVersion: v1
kind: Service
metadata:
  name: master-headless
spec:
  clusterIP: None
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
---
