---
apiVersion: v1
kind: Service
metadata:
  name: worker-headless
spec:
  clusterIP: None
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_SECRET
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_ACCOUNT
        - name: FAIL
          value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstable-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_SECRET
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_ACCOUNT
        - name: FAIL
          value: "1"