---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: NodePort 
  selector:
    app: master
  ports:
  - name: http
    port: 30001 # service port
    targetPort: 30000 # container port (internal access port)
    nodePort: 30001 # external access port
---
apiVersion: v1
kind: Service
metadata:
  name: master-headless
spec:
  clusterIP: None
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: master:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052 
        - containerPort: 30000   
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: WORKER_SERVICE
          value: "worker-headless.default.svc.cluster.local"
        - name: MASTER_SERVICE
          value: "master-headless.default.svc.cluster.local"
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_SECRET
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_ACCOUNT
        - name: FAIL
          value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstable-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: master:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052 
        - containerPort: 30000   
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_ENDPOINT
          value: "app-etcd.default.svc.cluster.local:2379"
        - name: WORKER_SERVICE
          value: "worker-headless.default.svc.cluster.local"
        - name: MASTER_SERVICE
          value: "master-headless.default.svc.cluster.local"
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CLIENT_SECRET
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_ACCOUNT
        - name: FAIL
          value: "5"

